name: Unit Testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit_testing:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Testing
        run: ./gradlew check

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
            name: unit-test-reports
            path: ./**/build/reports/tests/
